### ISSUE TITLE
Arguments to `hmac.digest` are in wrong order

### ISSUE THREAD

**Issue by odkr** [stevekerrison/auth-examples#5]
First, thanks a lot for your blog post and your example code! They were of great help in implementing SCRAM in a client I'm working on.

However, while implementing the client, I noticed a minor error; you mixed up the arguments for deriving the client key and server keys.

You write:

```python
client_key = hmac.digest(b'Client Key', salted_password, 'sha256')
server_key = hmac.digest(b'Server Key', salted_password, 'sha256')
```

But it should be:

```python
client_key = hmac.digest(salted_password, b'Client Key', 'sha256')
server_key = hmac.digest(salted_password, b'Server Key', 'sha256')
```

**Comment by stevekerrison** [comment]
Hi @odkr,

Delighted to see somebody read my article and/or code! Even more delighted to see you've found something wrong with it. Having checked [RFC5802](https://datatracker.ietf.org/doc/html/rfc5802) Section 2.4 (notation), indeed the order is `HMAC(key, msg)`, which matches the Python `hmac` implementation, and Section 3 agrees with you on the order; the password is the key, and the Client/Server key string is the message.

I'll try to update this tomorrow, but will review the other crypto calls against the documentation to make sure I didn't miss anything else out.

Thanks!

**Comment by odkr** [comment]
Happy to help :-)
