### ISSUE TITLE
"," and "=" should be escaped in usernames

### ISSUE THREAD

**Issue by odkr** [stevekerrison/auth-examples#6]
I just realised I had overlooked that "," and "=" have to be escaped in usernames:

> The characters ',' or '=' in usernames are sent as '=2C' and
> '=3D' respectively.  If the server receives a username that
> contains '=' not followed by either '2C' or '3D', then the
> server MUST fail the authentication (RFC 5802, sec. 5.1).

And I thought I'd bring that to your attention, because you seem to have overlooked it, too ;-).

**Comment by stevekerrison** [comment]
Took me a while, but this is fixed in 411df12dda935ed71d67a3ea6a2846e0061fd6f1. Thanks!
