### ISSUE TITLE
Need help about SCRAM

### ISSUE THREAD

**Issue by Neustradamus** [stevekerrison/auth-examples#7]
Dear @stevekerrison,

Can you help to have improvements in OpenSSL?

It is linked to:
- https://github.com/fabiang/sasl/issues/11

Thanks in advance.

**Comment by stevekerrison** [comment]
Replied in the original issue, so closing this one as it's now redundant.

**Comment by Neustradamus** [comment]
@stevekerrison: Thanks for your answer!

Can you check this request too, can you create a Qt.io account?
- https://bugreports.qt.io/browse/QTBUG-77783
